apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    cosi.storage.k8s.io/authors: Kubernetes Authors
    cosi.storage.k8s.io/license: Apache V2
    cosi.storage.k8s.io/support: https://github.com/kubernetes-sigs/container-object-storage-api
  labels:
    cosi.storage.k8s.io/version: dev
  name: objectstorage.k8s.io
parameters:
  disable.csi.storage.k8s.io/fstype: xfs
  disable.csi.storage.k8s.io/provisioner-secret-name: objectstorage.k8s.io
  disable.csi.storage.k8s.io/provisioner-secret-namespace: {{ .Release.Namespace }}
  fstype: xfs
provisioner: objectstorage.k8s.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    cosi.storage.k8s.io/authors: Kubernetes Authors
    cosi.storage.k8s.io/license: Apache V2
    cosi.storage.k8s.io/support: https://github.com/kubernetes-sigs/container-object-storage-api
  labels:
    app.kubernetes.io/component: csi-adapter
    app.kubernetes.io/name: objectstorage-csi-adapter
    app.kubernetes.io/part-of: cosi
    app.kubernetes.io/version: main
    cosi.storage.k8s.io/version: dev
  name: objectstorage-csi-adapter-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    cosi.storage.k8s.io/authors: Kubernetes Authors
    cosi.storage.k8s.io/license: Apache V2
    cosi.storage.k8s.io/support: https://github.com/kubernetes-sigs/container-object-storage-api
  labels:
    app.kubernetes.io/component: csi-adapter
    app.kubernetes.io/name: objectstorage-csi-adapter
    app.kubernetes.io/part-of: cosi
    app.kubernetes.io/version: main
    cosi.storage.k8s.io/version: dev
  name: objectstorage-csi-adapter
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - watch
  - list
  - delete
  - update
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    cosi.storage.k8s.io/authors: Kubernetes Authors
    cosi.storage.k8s.io/license: Apache V2
    cosi.storage.k8s.io/support: https://github.com/kubernetes-sigs/container-object-storage-api
  labels:
    app.kubernetes.io/component: csi-adapter
    app.kubernetes.io/name: objectstorage-csi-adapter
    app.kubernetes.io/part-of: cosi
    app.kubernetes.io/version: main
    cosi.storage.k8s.io/version: dev
  name: objectstorage-csi-adapter-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - objectstorage.k8s.io
  resources:
  - bucketrequests
  - bucketaccessrequests
  - buckets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - objectstorage.k8s.io
  resources:
  - bucketaccesses
  verbs:
  - get
  - list
  - watch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    cosi.storage.k8s.io/authors: Kubernetes Authors
    cosi.storage.k8s.io/license: Apache V2
    cosi.storage.k8s.io/support: https://github.com/kubernetes-sigs/container-object-storage-api
  labels:
    app.kubernetes.io/component: csi-adapter
    app.kubernetes.io/name: objectstorage-csi-adapter
    app.kubernetes.io/part-of: cosi
    app.kubernetes.io/version: main
    cosi.storage.k8s.io/version: dev
  name: objectstorage-csi-adapter
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: objectstorage-csi-adapter
subjects:
- kind: ServiceAccount
  name: objectstorage-csi-adapter-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    cosi.storage.k8s.io/authors: Kubernetes Authors
    cosi.storage.k8s.io/license: Apache V2
    cosi.storage.k8s.io/support: https://github.com/kubernetes-sigs/container-object-storage-api
  labels:
    app.kubernetes.io/component: csi-adapter
    app.kubernetes.io/name: objectstorage-csi-adapter
    app.kubernetes.io/part-of: cosi
    app.kubernetes.io/version: main
    cosi.storage.k8s.io/version: dev
  name: objectstorage-csi-adapter
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: objectstorage-csi-adapter-role
subjects:
- kind: ServiceAccount
  name: objectstorage-csi-adapter-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
data:
  key: none
kind: Secret
metadata:
  annotations:
    cosi.storage.k8s.io/authors: Kubernetes Authors
    cosi.storage.k8s.io/license: Apache V2
    cosi.storage.k8s.io/support: https://github.com/kubernetes-sigs/container-object-storage-api
  labels:
    cosi.storage.k8s.io/version: dev
  name: objectstorage.k8s.io
  namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    cosi.storage.k8s.io/authors: Kubernetes Authors
    cosi.storage.k8s.io/license: Apache V2
    cosi.storage.k8s.io/support: https://github.com/kubernetes-sigs/container-object-storage-api
  labels:
    app.kubernetes.io/component: csi-adapter
    app.kubernetes.io/name: objectstorage-csi-adapter
    app.kubernetes.io/part-of: cosi
    app.kubernetes.io/version: main
    cosi.storage.k8s.io/version: dev
  name: objectstorage-csi-adapter
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: csi-adapter
      app.kubernetes.io/name: objectstorage-csi-adapter
      app.kubernetes.io/part-of: cosi
      cosi.storage.k8s.io/version: dev
  template:
    metadata:
      annotations:
        cosi.storage.k8s.io/authors: Kubernetes Authors
        cosi.storage.k8s.io/license: Apache V2
        cosi.storage.k8s.io/support: https://github.com/kubernetes-sigs/container-object-storage-api
      labels:
        app.kubernetes.io/component: csi-adapter
        app.kubernetes.io/name: objectstorage-csi-adapter
        app.kubernetes.io/part-of: cosi
        app.kubernetes.io/version: main
        cosi.storage.k8s.io/version: dev
    spec:
      containers:
      - args:
        - --v=5
        - --csi-address=/csi/csi.sock
        - --kubelet-registration-path=/var/lib/kubelet/plugins/objectstorage.k8s.io/csi.sock
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.0.1
        name: node-driver-registrar
        securityContext:
          privileged: true
        terminationMessagePath: /var/logs/driver-registrar-termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
        - mountPath: /registration
          name: registration-dir
      - args:
        - --v=5
        - --identity=objectstorage.k8s.io
        - --listen=$(CSI_ENDPOINT)
        - --protocol=$(CSI_PROTO)
        - --node-id=$(KUBE_NODE_NAME)
        - --data-path=$(DATA_PATH)
        - --max-volumes=$(MAX_VOLUMES)
        env:
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        - name: CSI_PROTO
          value: unix
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: DATA_PATH
          value: /cosi-secret-dir
        - name: MAX_VOLUMES
          value: "100"
        image: quay.io/containerobjectstorage/objectstorage-csi-adapter:canary
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 10
          periodSeconds: 2
          timeoutSeconds: 3
        name: objectstorage-csi-adapter
        ports:
        - containerPort: 9898
          name: healthz
          protocol: TCP
        securityContext:
          privileged: true
        terminationMessagePath: /var/log/driver-termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
        - mountPath: /cosi-secret-dir
          mountPropagation: Bidirectional
          name: cosi-data-dir
        - mountPath: /var/lib/kubelet/pods
          mountPropagation: Bidirectional
          name: mountpoint-dir
      - args:
        - --csi-address=/csi/csi.sock
        - --health-port=9898
        image: k8s.gcr.io/sig-storage/livenessprobe:v2.2.0
        name: liveness-probe
        terminationMessagePath: /var/log/driver-liveness-termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
      serviceAccountName: objectstorage-csi-adapter-sa
      volumes:
      - hostPath:
          path: /var/lib/kubelet/plugins/objectstorage.k8s.io
          type: DirectoryOrCreate
        name: socket-dir
      - hostPath:
          path: /var/lib/kubelet/plugins_registry
          type: Directory
        name: registration-dir
      - hostPath:
          path: /var/lib/cosi-data/
          type: DirectoryOrCreate
        name: cosi-data-dir
      - hostPath:
          path: /var/lib/kubelet/pods
          type: DirectoryOrCreate
        name: mountpoint-dir
---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  annotations:
    cosi.storage.k8s.io/authors: Kubernetes Authors
    cosi.storage.k8s.io/license: Apache V2
    cosi.storage.k8s.io/support: https://github.com/kubernetes-sigs/container-object-storage-api
  labels:
    cosi.storage.k8s.io/version: dev
  name: objectstorage.k8s.io
spec:
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes:
  - Ephemeral
