---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    cosi.storage.k8s.io/authors: Nutanix Inc
    cosi.storage.k8s.io/license: Apache V2
    cosi.storage.k8s.io/support: https://github.com/kubernetes-sigs/container-object-storage-api
  labels:
    app.kubernetes.io/component: driver-ntnx
    app.kubernetes.io/name: cosi-driver-ntnx
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/version: main
  name: objectstorage-provisioner-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    cosi.storage.k8s.io/authors: Nutanix Inc
    cosi.storage.k8s.io/license: Apache V2
    cosi.storage.k8s.io/support: https://github.com/kubernetes-sigs/container-object-storage-api
  labels:
    app.kubernetes.io/component: driver-ntnx
    app.kubernetes.io/name: cosi-driver-ntnx
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/version: main
  name: objectstorage-provisioner-role
rules:
- apiGroups:
  - objectstorage.k8s.io
  resources:
  - buckets
  - bucketaccesses
  - buckets/status
  - bucketaccesses/status
  - bucketaccessclasses
  - bucketaccessclasses/status
  - bucketclaims
  - bucketclaims/status
  verbs:
  - get
  - list
  - watch
  - update
  - create
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - watch
  - list
  - delete
  - update
  - create
- apiGroups:
  - ""
  resources:
  - secrets
  - events
  verbs:
  - get
  - delete
  - update
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    cosi.storage.k8s.io/authors: Nutanix Inc
    cosi.storage.k8s.io/license: Apache V2
    cosi.storage.k8s.io/support: https://github.com/kubernetes-sigs/container-object-storage-api
  labels:
    app.kubernetes.io/component: driver-ntnx
    app.kubernetes.io/name: cosi-driver-ntnx
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/version: main
  name: objectstorage-provisioner-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: objectstorage-provisioner-role
subjects:
- kind: ServiceAccount
  name: objectstorage-provisioner-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
data:
  NTNX_DRIVER_IMAGE_ORG: ntnx
  NTNX_DRIVER_IMAGE_VERSION: latest
  OBJECTSTORAGE_PROVISIONER_IMAGE_ORG: quay.io/containerobjectstorage
  OBJECTSTORAGE_PROVISIONER_IMAGE_VERSION: canary
kind: ConfigMap
metadata:
  annotations:
    cosi.storage.k8s.io/authors: Nutanix Inc
    cosi.storage.k8s.io/license: Apache V2
    cosi.storage.k8s.io/support: https://github.com/kubernetes-sigs/container-object-storage-api
  labels:
    app.kubernetes.io/component: driver-ntnx
    app.kubernetes.io/name: cosi-driver-ntnx
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/version: main
    generated-by: kustomize
  name: cosi-driver-ntnx-config
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    cosi.storage.k8s.io/authors: Nutanix Inc
    cosi.storage.k8s.io/license: Apache V2
    cosi.storage.k8s.io/support: https://github.com/kubernetes-sigs/container-object-storage-api
  labels:
    app.kubernetes.io/component: driver-ntnx
    app.kubernetes.io/name: cosi-driver-ntnx
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/version: main
  name: objectstorage-provisioner
  namespace: {{ .Release.Namespace }}
stringData:
  ACCESS_KEY: {{ .Values.access_key }}
  ACCOUNT_NAME: {{ .Values.account_name }}
  ENDPOINT: {{ .Values.endpoint }}
  PC_SECRET: {{ .Values.pc_secret }}
  SECRET_KEY: {{ .Values.secret_key }}
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    cosi.storage.k8s.io/authors: Nutanix Inc
    cosi.storage.k8s.io/license: Apache V2
    cosi.storage.k8s.io/support: https://github.com/kubernetes-sigs/container-object-storage-api
  labels:
    app.kubernetes.io/component: driver-ntnx
    app.kubernetes.io/name: cosi-driver-ntnx
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/version: main
  name: objectstorage-provisioner
  namespace: {{ .Release.Namespace }}
spec:
  minReadySeconds: 30
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/component: driver-ntnx
      app.kubernetes.io/name: cosi-driver-ntnx
      app.kubernetes.io/part-of: container-object-storage-interface
      app.kubernetes.io/version: main
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cosi.storage.k8s.io/authors: Nutanix Inc
        cosi.storage.k8s.io/license: Apache V2
        cosi.storage.k8s.io/support: https://github.com/kubernetes-sigs/container-object-storage-api
      labels:
        app.kubernetes.io/component: driver-ntnx
        app.kubernetes.io/name: cosi-driver-ntnx
        app.kubernetes.io/part-of: container-object-storage-interface
        app.kubernetes.io/version: main
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: objectstorage-provisioner
        image: ghcr.io/nutanix-cloud-native/ntnx-cosi-driver:gts23
        imagePullPolicy: IfNotPresent
        name: ntnx-system
        volumeMounts:
        - mountPath: /var/lib/cosi
          name: socket
      - args:
        - --v=5
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - secretRef:
            name: objectstorage-provisioner
        image: gcr.io/k8s-staging-sig-storage/objectstorage-sidecar/objectstorage-sidecar@sha256:589c0ad4ef5d0855fe487440e634d01315bc3d883f91c44cb72577ea6e12c890
        imagePullPolicy: Always
        name: objectstorage-provisioner-sidecar
        volumeMounts:
        - mountPath: /var/lib/cosi
          name: socket
      serviceAccountName: objectstorage-provisioner-sa
      volumes:
      - emptyDir: {}
        name: socket
