---
global:
  pattern: multicluster-devsecops

  cicd:
    namespace: devsecops-ci

  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

  secure-registry:
    namespace: "openshift-storage"

  imageregistry:
    account: wolfgangntnx
    hostname: quay.io
    type: quay

  git:
    hostname: github.com
    account: wolfganghuse
    username: wolfganghuse
    email: wolfgang.huse@nutanix.com
    dev_revision: main

  quay:
    org:
      name: devel
      email: devel@myorg.com
    repo: example
  opp: true

main:
  clusterGroupName: hub
