---
global:
  pattern: multicluster-devsecops

  cicd:
    namespace: devsecops-ci

  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

  secure-registry:
    namespace: "openshift-storage"

  imageregistry:
    account: wolfgangntnx
    hostname: quay.io
    type: quay

  git:
    hostname: github.com
    account: wolfganghuse
    username: wolfganghuse
    email: wolfgang.huse@nutanix.com
    dev_revision: main

  quay:
    component:
    - name: clair
      managed: true
    - name: horizontalpodautoscaler
      managed: true
    - name: mirror
      managed: true
    - name: monitoring
      managed: true
    - name: postgres
      managed: false
    - name: redis
      managed: false
    - name: objectstorage
      managed: false
    - name: route
      managed: true
    - name: tls
      managed: true
    - name: quay
      managed: true
    - name: clairpostgres
      managed: true
    # Needs to be set consistently between hub and spoke clusters
    # TODO: Move back to the hub chart, store in a configmap, have an ACM policy distribute to spoke clusters, have spoke look up from configmap
    s3:
      host: objects.az01.ocpnvd.dachlab.net
      accesskey: dGjyM6XslvzU_2K80TT0PAibzMB7I31_
      secretkey: 96N2mcqGY_EIIbsc6WCoFVBz2wyBs2nQ
      bucket: quay
    org:
      name: devel
      email: devel@myorg.com
    repo: example
  opp: true

main:
  clusterGroupName: hub
