apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: CA Assessment Authorization and
      Monitoring
    policy.open-cluster-management.io/controls: CA-7 Continuous Monitoring
    policy.open-cluster-management.io/standards: NIST SP 800-53
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    open-cluster-management.io/policy-set: openshift-plus
  name: policy-ocm-observability
  namespace: policies
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-ocm-observability
        annotations:
          argocd.argoproj.io/compare-options: IgnoreExtraneous
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Secret
            metadata:
              name: thanos-object-storage
              namespace: open-cluster-management-observability
            stringData:
              thanos.yaml: |
                type: s3
                config:
                  bucket: observability
                  endpoint: objects.az01.ocpnvd.dachlab.net
                  insecure: true
                  access_key: ewZp6W8ggr8E6kX7e6SweMPTDI1MpbtY
                  secret_key: WNR4Wa-Ut0fbkdTgLZDpZLd0zOgwzzIf
              type: Opaque
        - complianceType: musthave
          objectDefinition:
            apiVersion: observability.open-cluster-management.io/v1beta2
            kind: MultiClusterObservability
            metadata:
              name: observability
            spec:
              observabilityAddonSpec: {}
              storageConfig:
                metricObjectStorage:
                  key: thanos.yaml
                  name: thanos-object-storage
        remediationAction: enforce
        severity: medium