apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: quay-registry
  namespace: quay-enterprise
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    openshift.io/node-selector: 'node-role.kubernetes.io/infra='
    scheduler.alpha.kubernetes.io/defaultTolerations: >-
      [{"operator": "Exists", "effect": "NoSchedule", "key":
      "node-role.kubernetes.io/infra"}
      ]
spec:
  components:
{{- range .Values.quay.component }}
    - kind: {{ .name }}
      managed: {{ .managed | default "false" }}
{{- end }}
{{- if .Values.quay.configBundleSecret.deploy }}
  configBundleSecret: {{ .Values.quay.configBundleSecret.name }}
{{- end }}
